#include "red_black_tree.h"
#include <iostream>

using namespace cop5536;
int main() {
  rb_tree<> *rbt = new rb_tree<>();
  std::cout << "insert 1, ";
  rbt->insert(1, 11.1);
  //rbt->print_in_order();
  std::cout << "2, ";
  rbt->insert(2, 119.1);
  //rbt->print_in_order();
  std::cout << "3, ";
  rbt->insert(3, 19.1);
  //rbt->print_in_order();
  std::cout << "4,";
  rbt->insert(4, 19.2);
  //rbt->print_in_order();
  std::cout << "5,";
  rbt->insert(5, 19.4);
  //rbt->print_in_order();
  std::cout << "6,";
  rbt->insert(6, 1.2);
  //rbt->print_in_order();
  std::cout << "7,";
  rbt->insert(7, 1.2);
  //rbt->print_in_order();
  std::cout << "8,";
  rbt->insert(8, 1.2);
  //rbt->print_in_order();
  std::cout << "9,";
  rbt->insert(9, 1.2);
  //rbt->print_in_order();
  std::cout << "10,";
  rbt->insert(10, 1.2);
  //rbt->print_in_order();
  std::cout << "20,";
  rbt->insert(20, 1.2);
  //rbt->print_in_order();
  std::cout << "19,";
  rbt->insert(19, 1.2);
  //rbt->print_in_order();
  std::cout << "18,";
  rbt->insert(18, 1.2);
  //rbt->print_in_order();
  std::cout << "17,";
  rbt->insert(17, 1.2);
  //rbt->print_in_order();
  std::cout << "16,";
  rbt->insert(16, 1.2);
  //rbt->print_in_order();
  std::cout << "15,";
  rbt->insert(15, 1.2);
  //rbt->print_in_order();
  std::cout << "14,";
  rbt->insert(14, 1.2);
  //rbt->print_in_order();
  std::cout << "13,";
  rbt->insert(13, 1.2);
  //rbt->print_in_order();
  std::cout << "12,";
  rbt->insert(12, 1.2);
  //rbt->print_in_order();
  std::cout << "11,";
  rbt->insert(11, 1.2);
  std::cout << std::endl;
  //rbt->print_in_order();
  std::cout << rbt->search(-222) << std::endl;
  // rbt->search(-1, 5);
  std::cout << std::endl;
  //rbt->search(12, 34);
  
  return 0;
}
