cop5536::bp_tree
std::ofstream cop5536::bp_tree::output
unsigned short cop5536::bp_tree::degree
bp_node* cop5536::bp_tree::root
cop5536::bp_tree::bp_tree()
cop5536::bp_tree::bp_tree(unsigned short m)
References open_output.
cop5536::bp_tree::~bp_tree()
References close_output.
void cop5536::bp_tree::insert(int key, float value)
References cop5536::rb_tree< key_type, data_type, node_type >::insert, cop5536::bp_node::is_leaf, cop5536::bp_node::insert_, cop5536::bp_node_i::children, cop5536::rb_tree_node< key_type, data_type >::key, cop5536::bp_node_i::first_child, cop5536::rb_tree_node< key_type, data_type >::data, cop5536::bp_node::node_size, cop5536::bp_node_i::split.
Referenced by main.
void cop5536::bp_tree::search(int key)
References cop5536::bp_node::search.
Referenced by main.
void cop5536::bp_tree::search(int low, int high)
References cop5536::bp_node::search.
void cop5536::bp_tree::remove(int key)
References cop5536::bp_node::is_leaf, cop5536::bp_node_l::data, cop5536::rb_tree< key_type, data_type, node_type >::delete_key, cop5536::bp_node_i::children, cop5536::rb_tree_node< key_type, data_type >::key, cop5536::bp_node_i::first_child, cop5536::rb_tree_node< key_type, data_type >::data, cop5536::bp_node::remove.
void cop5536::bp_tree::print()
References cop5536::bp_node::print.
Referenced by main.
void cop5536::bp_tree::open_output()
References OUTPUT.
Referenced by bp_tree.
void cop5536::bp_tree::close_output()
Referenced by ~bp_tree.