cop5536::bp_node
unsigned short cop5536::bp_node::node_size
Referenced by cop5536::bp_tree::insert, cop5536::bp_node_i::insert_, cop5536::bp_node_l::insert_, cop5536::bp_node_l::split, cop5536::bp_node_i::split, cop5536::bp_node_l::remove, cop5536::bp_node_i::remove, cop5536::bp_node_i::print, cop5536::bp_node_l::print.
cop5536::bp_node::bp_node()
cop5536::bp_node::bp_node(unsigned short ns)
virtual cop5536::bp_node::~bp_node()
virtual void cop5536::bp_node::destory_()=0
Referenced by cop5536::bp_node_i::destory_.
virtual void cop5536::bp_node::print()=0
Referenced by cop5536::bp_tree::print, cop5536::bp_node_i::print.
virtual bool cop5536::bp_node::is_leaf()=0
Referenced by cop5536::bp_node_i::destory_, cop5536::bp_tree::insert, cop5536::bp_node_i::remove, cop5536::bp_tree::remove.
bool cop5536::bp_node::is_full(unsigned short degree)
virtual float cop5536::bp_node::search(int key)=0
Referenced by cop5536::bp_node_i::search, cop5536::bp_tree::search.
virtual std::vector<float>* cop5536::bp_node::search(int low, int high)=0
virtual bool cop5536::bp_node::remove(int key)=0
Referenced by cop5536::bp_node_i::remove, cop5536::bp_tree::remove.
virtual bool cop5536::bp_node::splitable()
Referenced by cop5536::bp_node_i::remove.
virtual rb_tree_node<int, bp_node*>* cop5536::bp_node::split(bool is_left)=0
Referenced by cop5536::bp_node_i::remove.
virtual rb_tree_node<int, bp_node *>* cop5536::bp_node::insert_(int key, float value, unsigned short degree)=0
Referenced by cop5536::bp_tree::insert, cop5536::bp_node_i::insert_.