cop5536::bp_node_i
bp_node* cop5536::bp_node_i::first_child
Referenced by destory_, cop5536::bp_tree::insert, insert_, split, remove, cop5536::bp_tree::remove, search, print.
rb_tree<int, bp_node*>* cop5536::bp_node_i::children
Referenced by destory_, cop5536::bp_tree::insert, insert_, split, remove, cop5536::bp_tree::remove, search, print.
cop5536::bp_node_i::bp_node_i()=delete
Referenced by split.
cop5536::bp_node_i::bp_node_i(unsigned short ns, bp_node *fc, rb_tree< int, bp_node * > *children)
virtual cop5536::bp_node_i::~bp_node_i() override
References destory_.
void cop5536::bp_node_i::destory_() override
References first_child, cop5536::bp_node::is_leaf, cop5536::bp_node::destory_, children.
Referenced by ~bp_node_i.
void cop5536::bp_node_i::print() override
References children, cop5536::bp_node::node_size, first_child, cop5536::bp_node::print.
virtual bool cop5536::bp_node_i::is_leaf() override
float cop5536::bp_node_i::search(int key) override
References children, cop5536::rb_tree_node< key_type, data_type >::key, first_child, cop5536::bp_node::search, cop5536::rb_tree_node< key_type, data_type >::data.
std::vector< float > * cop5536::bp_node_i::search(int low, int high) override
References first_child, cop5536::bp_node::search, children.
bool cop5536::bp_node_i::remove(int key) override
References children, cop5536::rb_tree_node< key_type, data_type >::key, first_child, cop5536::rb_tree_node< key_type, data_type >::data, cop5536::bp_node::remove, cop5536::bp_node::is_leaf, cop5536::bp_node::splitable, cop5536::bp_node::split, cop5536::bp_node::node_size.
rb_tree_node< int, bp_node * > * cop5536::bp_node_i::split(bool is_left) override
References cop5536::bp_node::node_size, children, bp_node_i, first_child.
Referenced by cop5536::bp_tree::insert, insert_.
rb_tree_node< int, bp_node * > * cop5536::bp_node_i::insert_(int key, float value, unsigned short degree) override
References children, cop5536::rb_tree_node< key_type, data_type >::key, first_child, cop5536::rb_tree_node< key_type, data_type >::data, cop5536::bp_node::insert_, cop5536::bp_node::node_size, split.